version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "7000:80"
    container_name: nuxtjs-app
    volumes:
      - .:/nuxtjs-app
    networks:
      - nuxtjs_network

networks:
  nuxtjs_network:
    name: nuxtjs_network
    driver: bridge
